config/routes.rb
Rails.application.routes.draw do
  
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users
  root to: 'pages#home'
  get '/dashboard' => "users#index"
  resources :trackers, except: [:index] do
    resources :added_games, only: %i[new create destroy]
  end
end

app/models/added_game.rb
class AddedGame < ApplicationRecord
  belongs_to :tracker
  belongs_to :game

  validates :game, uniqueness: { scope: :tracker}
  GAMES = Game.all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :added_games
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  belongs_to :user
  has_many :added_games, dependent: :destroy
  has_many :games, through: :added_games

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :trackers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/added_games_controller.rb
class AddedGamesController < ApplicationController
  before_action :set_tracker, only: %i[new create destroy]

  def new
    @addedgame = AddedGame.new
    authorize @addedgame
  end

  def create
    @addedgame = AddedGame.new(added_game_params)
    @addedgame.tracker = @tracker
    authorize @addedgame
    if @addedgame.save
      flash[:notice] = "#{@addedgame.game.title} successfully added to #{@tracker.name}"
      redirect_to tracker_path(@tracker)
    else
      flash[:alert] = "This game might already be in this tracker. If not, try again later or contact support."
      redirect_to new_tracker_added_game_path(@tracker)
    end
  end 

  def destroy
    @addedgame = AddedGame.find(params[:id])
    authorize @addedgame
    if @addedgame.destroy
      flash[:notice] = "#{@addedgame.game.title} successfully removed from #{@addedgame.tracker.name}"
      redirect_to tracker_path(@tracker)
    else
      flash[:alert] = "Something went wrong. Try again later."
      redirect_to edit_tracker_path(@tracker)
    end
  end

  private

  def added_game_params
    params.require(:added_game).permit(:game_id)
  end

  def set_tracker
    @tracker = Tracker.find(params[:tracker_id])
    authorize @tracker
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def after_sign_in_path_for(*)
    dashboard_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: %i[show edit update destroy]

  def new
    @tracker = Tracker.new
    authorize @tracker
  end

  def create
    @tracker = Tracker.new(tracker_params)
    @tracker.user = current_user
    authorize @tracker
    if @tracker.save
      flash[:notice] = "#{@tracker.name} successfully created!"
      redirect_to dashboard_path
    else
      flash[:alert] = "Something went wrong. Please try again."
      redirect_to new_tracker_path
    end
  end

  def show
    # Need to figure out a way to make this work for every game as scraping is dependent on classes which are different for every site.
    # Store class names in the game model? Still needs manual checking.
    # Any way to automate the process?
    @games = @tracker.games
    @games.each do |game|
      case game.title
      when "BDO"
        gon.bdo = game.content
      when "Guild Wars 2"
        gon.gw2 = game.content
      end
    end
  end

  def edit
    @addedgames = AddedGame.where(tracker: @tracker)
  end

  def update
    if @tracker.update(tracker_params)
      flash[:notice] = "#{@tracker.name} successfully updated"
      redirect_to tracker_path(@tracker)
    else
      flash[:alert] = "Somethign went wrong and #{@tracker.name} could not be updated. Please try again"
      redirect_to edit_tracker_path(@tracker)
    end
  end

  def destroy
    if @tracker.destroy
      flash[:notice] = "#{@tracker.name} successfully deleted"
      redirect_to dashboard_path
    else
      flash[:alert] = "#{@tracker.name} could not be deleted. Please try again"
      redirect_to tracker_path(@tracker)
    end
  end

  private

  def set_tracker
    @tracker = Tracker.find(params[:id])
    authorize @tracker
  end

  def tracker_params
    params.require(:tracker).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @trackers = policy_scope(Tracker)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/added_games/new.html.erb
<div class="container">
  <h1>Add a new game to <%= @tracker.name %></h1>

  <%= simple_form_for [@tracker, @addedgame] do |f| %>
    <%= f.input :game_id, collection: AddedGame::GAMES, label: "Choose the game you'd wish to add to your tracker" %>
    <%= f.submit "Add Game" %>
  <% end %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gametracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= include_gon %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  Todo:
  <ol>
    <li>Create and populate landing page</li>
    <li>Create models for the tracker and added_games</li>
  </ol>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/dx6rtf9wl/image/upload/v1615222704/user_xyjx1w.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/trackers/edit.html.erb
<div class="container">
  <h2>Editing <%= @tracker.name %></h2>
  <%= simple_form_for @tracker do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>

  <% @addedgames.each do |game| %>
    <p><%= game.game.title %> <%= link_to "x", tracker_added_game_path(@tracker, game), method: :delete, data: { confirm: "Are you sure you wish to delete this game from the tracker?"} %></p>
  <% end %>
</div>

app/views/trackers/new.html.erb
<div class="container">
  <h1>Create a new tracker</h1>

  <%= simple_form_for @tracker do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
  
</div>

app/views/trackers/show.html.erb
<div class="container">
  <h1><%= @tracker.name %></h1>
  <%= link_to "Edit this tracker", edit_tracker_path(@tracker)  %>
  <%= link_to "Delete this tracker", tracker_path(@tracker), method: :delete  %>
  <%= link_to "Add game", new_tracker_added_game_path(@tracker)  %>

  <h4>List of games in this tracker</h4>

  <ul class="nav nav-tabs" id="gamesTab" role="tablist">
  <% @tracker.games.each do |game| %>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="g<%= game.id %>-tab" data-toggle="tab" href="#g<%= game.id %>" role="tab" aria-controls="g<%= game.id %>" aria-selected="false"><%= game.title %></a>
    </li>
  <% end %>
  </ul>
  <div class="tab-content" id="gamesTabContent">
  <% @tracker.games.each do |game| %>
    <div class="tab-pane fade" id="g<%= game.id %>" role="tabpanel" aria-labelledby="g<%= game.id %>-tab"><%= game.content %></div>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  Your trackers
  <%= link_to "Add a new tracker", new_tracker_path %>
  <ul>
    <% @trackers.each do |tracker| %>
      <li><%= link_to tracker.name, tracker_path(tracker)%></li>
    <% end %>
  </ul>
</div>